name: "Build on new release"
run-name: "Perform build for release ${{ github.ref }}"
on:
  release:
    types: [created]
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: write
    steps:
      - uses: "actions/checkout@v5"
      - name: "Determine version"
        run: |
          echo ${{ github.ref }} | sed -e "s/refs\/tags\///" > __VERSION
          echo ezdoc-wpcf7-$(cat __VERSION).zip > __FILE_NAME
      - name: "Zip content"
        run: "zip $(cat __FILE_NAME) ezdoc-wpcf7.php LICENSE readme.txt public admin includes assets"
      - name: "Upload zip"
        run: "gh release upload $(cat __VERSION) $(cat __FILE_NAME)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}