name: "Build on new release"
run-name: "Perform build for release ${{ github.ref }}"
on:
  release:
    types: [created]
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: write
    steps:
      - name: "Install Necessary Packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
      - uses: "actions/checkout@v5"
      - name: "Determine version"
        run: |
          echo ${{ github.ref }} | sed -e "s/refs\/tags\///" > __VERSION
          echo ez-doc-integration-for-contact-form-7.zip > __FILE_NAME
      - name: "Compile PO Files"
        working-directory: ./languages
        run: |
          for file in `find . -name "*.po"` ; do msgfmt -o ${file/.po/.mo} $file ; done
          rm *.po *.pot
      - name: "Zip content"
        run: |
          zip -r $(cat __FILE_NAME) ez-doc-integration-for-contact-form-7.php LICENSE readme.txt public admin includes languages
      - name: "Upload zip"
        run: |
          gh release upload $(cat __VERSION) $(cat __FILE_NAME)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}